### ISSUE TITLE
HLS VI: Add metadata and STAC generation capabilities

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/hls-project#10]
## Description
Finish scripts that generate VI granule metadata 

## Acceptance Criteria
- [x] Create metadata generation script

**Comment by madhuksridhar** [comment]
https://github.com/NASA-IMPACT/hls-vi/blob/dev/hls-vi/hls_vi_metadata_creator.py

**Comment by SwordSaintLancelot** [comment]
The STAC CMR metadata xml file is generated and validated with the general schema. Below is the screenshot showing the assertValid function confirming that the XML created is in accordance with the general schema.
![Image](https://github.com/NASA-IMPACT/hls-project/assets/34275219/7a982cc9-f3f1-4a27-a35f-a0ca886579b0)

In the screenshot, `temp1` variable contains the general `xml` schema while `temp2` contains the `hls-vi` schema. Asserting them with each other does not result in any error.
