### ISSUE TITLE
HLS-VI paper

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/hls-project#37]
### Description
HLS-VI journal paper

### Acceptance Criteria
- [ ] Analyze the spatial consistency of VI
- [ ] Analyze the temporal consistency of VI
- [ ] Draft initial paper
- [ ] Sent the draft paper to co-authors for review and reconcile comments
- [ ] Sent the paper to journal for review and reconcile comments
- [ ] Publish paper

**Comment by madhuksridhar** [comment]
@bwbaker1 Is this a duplicate of Qiang's paper? If so can we link his ticket and close this?
